### ISSUE TITLE
Learn Rails 2. A model is born.

### ISSUE THREAD

**Issue by patrickquigley102** [awalsh3/books#2]
# Wider Context

## Goal.

Learn more about the Model layer in Rails.

## Application Overview.

We’re building an API powered by Rails. The API will serve data about Books.

Call the Application books.

We’ll use SQLite for our Database because, it does not require a second service running a database. This is simpler for us.

We’re not concerned with deploying it to the WWW currently, we only care about it running locally.

We’re not concerned about responding to HTTP requests with Web Pages, only data. So we can ignore all View/JS/HTML/CSS etc concerns.

# This issue

A book, that has author name, title and description.
Add validation that every book must have an author and a unique title.
Add seed data to create 10 book.

Side note: Do you write unit tests? If you do then do for all these chunks. If you don’t then no worries.

**Comment by patrickquigley102** [comment]
Copying notes over from Google Doc.

```
rails g model Book author_name title description
validates :author_name, presence: true -------- validates :title, uniqueness: true
puts 'Creating books...'
book1 = Book.new(author_name: “JK Rowling”, title: "Harry Potter", description: “Magic and wizards and witches”)
Book1.save!
x9
puts 'Finished!'
-- OR --
require 'faker'
puts 'Creating 10 fake books...'
10.times do
  book = book.new(
    title:    [Faker::Book](https://github.com/faker-ruby/faker/blob/main/doc/books/book.md),
    author_name: Faker::Book.author,
    description: Faker::Book.genre,
    rating:  rand(0..5)
    word_count: rand(500..1890)
  )
  book.save!
End
puts 'Finished!'
```

**Comment by awalsh3** [comment]
Unit tests: on branch 'rspec'

I installed RSPEC and added a book_spec.rb file to create validity tests. 
Should have done this first so that when the new attributes were added, it would have failed the tests and I would have fixed them! 
This file needs a refactor but I've run out of time.
