### ISSUE TITLE
Learn Rails 5. GET books endpoint.

### ISSUE THREAD

**Issue by patrickquigley102** [awalsh3/books#5]
# Wider Context

## Goal.

Learn more about the Controller layer in Rails.

## Application Overview.

We’re building an API powered by Rails. The API will serve data about Books.

Call the Application books.

We’ll use SQLite for our Database because, it does not require a second service running a database. This is simpler for us.

We’re not concerned with deploying it to the WWW currently, we only care about it running locally.

We’re not concerned about responding to HTTP requests with Web Pages, only data. So we can ignore all View/JS/HTML/CSS etc concerns.

# This issue

We're making an index route for books. 

### Requirements

- We want a route at `APP_ROOT/books` that returns a list of books. 
- This endpoint should be compliant with [JSON API](https://jsonapi.org/) specification.
- The endpoint should return all book attributes in it's response. If there is a DB field, in should be in the response.
- Successful response only. We're only interested in the happy path for now, in a 200 response with a list of books.
- No new gems. Keep it simple and implement this using Rails + our own code only.

### Planning

If you want to plan the work out yourself go for it. I've added some pointers below but they're hidden, so you can engage with them as much as you like. 

Whatever plan you choose, please record it on this ticket before starting any coding. So we can discuss planning as well as delivery.

<details>
  <summary>Spoiler. Sample HTTP request + response. Will help with understand JSON API spec </summary>
  
```
# HTTP request
## headers
Content-Type: application/vnd.api+json
## verb
GET 
## route
[app_domain:port]/books

# HTTP response
## headers
Content-Type: application/vnd.api+json
## status
200
## body
{
  "type": "books",
  "id": "1",
  "attributes": {
    "name": "name"
    # other attributes
  }
}
```
  
</details>

<details>
  <summary>Spoiler. Task broken down into steps. </summary>
  
- Request. Add books resources route, with only index action.
- Request. Add controller with index action.
- Response. Mock books as empty array.
- Response. Get the headers compliant with JSON spec.
- Response. Get the body returning JSON structured correctly, still using empty array (no books) mocked data.
  - See the http sample response.
- Response. Stitch the actual books into the JSON body, this is called serialization.
  - Serialization: https://medium.com/@maxfpowell/a-quick-intro-to-rails-serializers-b390ced1fce7
  
</details>

**Comment by awalsh3** [comment]
Plan: the plan is to use the spoiler task breakdown as I am unfamiliar with API-only apps.
Quick question before I dive in... is there some config missing that I'll need to add in order for this to work? Each tutorial I google creates an example app using --api as an arg... 
Can you guide me as to if this might be what is needed? --> https://guides.rubyonrails.org/api_app.html#changing-an-existing-application

**Comment by patrickquigley102** [comment]
Hey Annie.

You'll be writing a endpoint in Rails that returns JSON, instead of a HTML document (and associated assets).

You're existing Rails application will almost certainly be capable of doing this.

So you can try cracking on with any configuration changes at the App level.

We're learning by doing, give it a try and see.

**Comment by awalsh3** [comment]
Create an array to hold the serialized book data

**Comment by awalsh3** [comment]
Ok, thank you!

Create an empty array to hold the book data
Iterate over each book record and format the data as a JSON API compliant  - type, id, attributes 
Format the response as a JSON compliant - data, meta
Render as JSON - to_json 
( I got super stuck here. Could not figure out how to get the headers to match the example http response) 
Think I am on to something now!
