### ISSUE TITLE
Project settings change.

### ISSUE THREAD

**Issue by patrickquigley102** [awalsh3/books#9]
In GitLab you can configure a project's PRs to lose approval if any code changes are pushed up.

Can you look seeing if the same is possible here too please?

**Comment by awalsh3** [comment]
<img width="778" alt="Screenshot 2023-04-19 at 12 06 21" src="https://user-images.githubusercontent.com/45202346/233056509-d422b11e-74bb-4191-9b13-2788afa315aa.png">

I believe this should do it!
